export const DRAWER_ITEMS = [
  "PRO",
  "Add Tournament",
  "Start A Match",
  "Go Live",
  "My Performance",
  "Leaderboards",
  "Awards",
  "Associations",
  "Clubs",
  "Contact",
  "Share App",
  "Rate Us",
  "App Code",
  "What's New",
  "Change Language",
  "Social Links",
  "About",
  "Blog",
  "FAQ",
  "Privacy Policy",
  "Terms",
];
