# Imports the *public* half of the deploy keypair only. The private half is
# generated by the operator and stored solely as the GitHub Actions secret
# EC2_SSH_PRIVATE_KEY - it never passes through Terraform or its state.
resource "aws_key_pair" "deploy" {
  key_name   = "${var.project_name}-deploy-key"
  public_key = var.ssh_public_key

  tags = {
    Project = var.project_name
  }
}
