export const SIDEBAR_LINKS = [
  { label: "Dashboard", path: "/", implemented: true },
  { label: "Users", path: "/users", implemented: false },
  { label: "Players", path: "/players", implemented: false },
  { label: "Teams", path: "/teams", implemented: false },
  { label: "Matches", path: "/matches", implemented: false },
  { label: "Live Matches", path: "/live-matches", implemented: false },
  { label: "Streaming", path: "/streaming", implemented: false },
  { label: "Tournaments", path: "/tournaments", implemented: false },
  { label: "Community", path: "/community", implemented: false },
  { label: "Looking", path: "/looking", implemented: false },
  { label: "Posts", path: "/posts", implemented: false },
  { label: "Videos", path: "/videos", implemented: false },
  { label: "Highlights", path: "/highlights", implemented: false },
  { label: "Store", path: "/store", implemented: false },
  { label: "Products", path: "/products", implemented: false },
  { label: "Orders", path: "/orders", implemented: false },
  { label: "Payments", path: "/payments", implemented: false },
  { label: "Subscriptions", path: "/subscriptions", implemented: false },
  { label: "Advertisements", path: "/advertisements", implemented: false },
  { label: "Notifications", path: "/notifications", implemented: false },
  { label: "Reports", path: "/reports", implemented: false },
  { label: "Moderation", path: "/moderation", implemented: false },
  { label: "Analytics", path: "/analytics", implemented: false },
  { label: "Settings", path: "/settings", implemented: false },
];
